webHibiscus/Controllers/ResenniaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webHibiscus;

namespace webHibiscus.Controllers
{
    public class ResenniaController : Controller
    {
        private webHibiscuEntities db = new webHibiscuEntities();

        // GET: Resennia
        public ActionResult Index()
        {
            var resennias = db.Resennias.Include(r => r.AspNetUser);
            return View(resennias.ToList());
        }

        // GET: Resennia/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resennia resennia = db.Resennias.Find(id);
            if (resennia == null)
            {
                return HttpNotFound();
            }
            return View(resennia);
        }

        // GET: Resennia/Create
        public ActionResult Create()
        {
            ViewBag.id_Cliente = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Resennia/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_Resenia,cotenido,id_Cliente,puntuacion,fecha")] Resennia resennia)
        {
            if (ModelState.IsValid)
            {
                db.Resennias.Add(resennia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_Cliente = new SelectList(db.AspNetUsers, "Id", "Email", resennia.id_Cliente);
            return View(resennia);
        }

        // GET: Resennia/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resennia resennia = db.Resennias.Find(id);
            if (resennia == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_Cliente = new SelectList(db.AspNetUsers, "Id", "Email", resennia.id_Cliente);
            return View(resennia);
        }

        // POST: Resennia/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_Resenia,cotenido,id_Cliente,puntuacion,fecha")] Resennia resennia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(resennia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_Cliente = new SelectList(db.AspNetUsers, "Id", "Email", resennia.id_Cliente);
            return View(resennia);
        }

        // GET: Resennia/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resennia resennia = db.Resennias.Find(id);
            if (resennia == null)
            {
                return HttpNotFound();
            }
            return View(resennia);
        }

        // POST: Resennia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Resennia resennia = db.Resennias.Find(id);
            db.Resennias.Remove(resennia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webHibiscus/Controllers/ReservaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webHibiscus;

namespace webHibiscus.Controllers
{
    public class ReservaController : Controller
    {
        private webHibiscuEntities db = new webHibiscuEntities();

        // GET: Reserva
        public ActionResult Index()
        {
            var reservas = db.Reservas.Include(r => r.AspNetUser).Include(r => r.AspNetUser1).Include(r => r.Servicio);
            return View(reservas.ToList());
        }

        // GET: Reserva/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reserva reserva = db.Reservas.Find(id);
            if (reserva == null)
            {
                return HttpNotFound();
            }
            return View(reserva);
        }

        // GET: Reserva/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servicio servicio = db.Servicios.Find(id);
            if (servicio == null)
            {
                return HttpNotFound();
            }

            ViewBag.id_Cliente = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.id_Empleado = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.id_Servicio = new SelectList(db.Servicios, "id_Servicio", "nombre", servicio.id_Servicio);

            return View();
        }

        // POST: Reserva/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_Reserva,fecha_Hora,id_Cliente,id_Empleado,id_Servicio")] Reserva reserva)
        {
            if (ModelState.IsValid)
            {
                db.Reservas.Add(reserva);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_Cliente = new SelectList(db.AspNetUsers, "Id", "Email", reserva.id_Cliente);
            ViewBag.id_Empleado = new SelectList(db.AspNetUsers, "Id", "Email", reserva.id_Empleado);
            ViewBag.id_Servicio = new SelectList(db.Servicios, "id_Servicio", "nombre", reserva.id_Servicio);
            return View(reserva);
        }

        // GET: Reserva/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reserva reserva = db.Reservas.Find(id);
            if (reserva == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_Cliente = new SelectList(db.AspNetUsers, "Id", "Email", reserva.id_Cliente);
            ViewBag.id_Empleado = new SelectList(db.AspNetUsers, "Id", "Email", reserva.id_Empleado);
            ViewBag.id_Servicio = new SelectList(db.Servicios, "id_Servicio", "nombre", reserva.id_Servicio);
            return View(reserva);
        }

        // POST: Reserva/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_Reserva,fecha_Hora,id_Cliente,id_Empleado,id_Servicio")] Reserva reserva)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reserva).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_Cliente = new SelectList(db.AspNetUsers, "Id", "Email", reserva.id_Cliente);
            ViewBag.id_Empleado = new SelectList(db.AspNetUsers, "Id", "Email", reserva.id_Empleado);
            ViewBag.id_Servicio = new SelectList(db.Servicios, "id_Servicio", "nombre", reserva.id_Servicio);
            return View(reserva);
        }

        // GET: Reserva/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reserva reserva = db.Reservas.Find(id);
            if (reserva == null)
            {
                return HttpNotFound();
            }
            return View(reserva);
        }

        // POST: Reserva/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reserva reserva = db.Reservas.Find(id);
            db.Reservas.Remove(reserva);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webHibiscus/Controllers/ServicioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webHibiscus;

namespace webHibiscus.Controllers
{
    public class ServicioController : Controller
    {
        private webHibiscuEntities db = new webHibiscuEntities();

        // GET: Servicio
        public ActionResult Index()
        {
            return View(db.Servicios.ToList());
        }

        // GET: Servicio/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servicio servicio = db.Servicios.Find(id);
            if (servicio == null)
            {
                return HttpNotFound();
            }
            return View(servicio);
        }

        // GET: Servicio/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Servicio/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_Servicio,descripcion,precio,nombre")] Servicio servicio)
        {
            if (ModelState.IsValid)
            {
                db.Servicios.Add(servicio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(servicio);
        }

        // GET: Servicio/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servicio servicio = db.Servicios.Find(id);
            if (servicio == null)
            {
                return HttpNotFound();
            }
            return View(servicio);
        }

        // POST: Servicio/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_Servicio,descripcion,precio,nombre")] Servicio servicio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(servicio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(servicio);
        }

        // GET: Servicio/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servicio servicio = db.Servicios.Find(id);
            if (servicio == null)
            {
                return HttpNotFound();
            }
            return View(servicio);
        }

        // POST: Servicio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Servicio servicio = db.Servicios.Find(id);
            db.Servicios.Remove(servicio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webHibiscus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    Styles
    <link href="~/Content/estilos.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/cardStyle.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/starability-all.css" rel="stylesheet" />


    <!-- Boxicons CDN Link -->
    <link href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
          rel="stylesheet" />

</head>
<body>
    <div class="sidebar">
        <div class="logo_content">
            <div class="logo">
                <i class='bx bxs-florist'></i>
                <div class="logo_name">Hibiscus</div>
            </div>
            <i class="bx bx-menu" id="btn"></i>
        </div>
        @*List of options*@
        <ul class="nav_list">
            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a href="@Url.Action("Index", "Home")">
                        <i class='bx bxs-home'></i>
                        <span class="links_name">Home</span>
                    </a>
                    <span class="tooltip">Home</span>
                </li>
                <li>
                    <a href="@Url.Action("Index", "AspNetUsers")">
                        <i class='bx bx-user'></i>
                        <span class="links_name">Usuarios</span>
                    </a>
                    <span class="tooltip">Usuarios</span>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Resennia")">
                        <i class='bx bx-comment-dots'></i>
                        <span class="links_name">Reseñas</span>
                    </a>
                    <span class="tooltip">Reseñas</span>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Reserva")">
                        <i class='bx bx-book-content'></i>
                        <span class="links_name">Reservas</span>
                    </a>
                    <span class="tooltip">Reservas</span>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Servicio")">
                        <i class='bx bx-briefcase-alt-2'></i>
                        <span class="links_name">Servicios</span>
                    </a>
                    <span class="tooltip">Servicios</span>
                </li>
                <li>
                    <a href="@Url.Action("About", "Home")">
                        <i class='bx bx-detail'></i>
                        <span class="links_name">Accerca</span>
                    </a>
                    <span class="tooltip">Accerca</span>
                </li>
            }

            @if (User.IsInRole("Cliente"))
            {
                <li>
                    <a href="@Url.Action("Index", "Home")">
                        <i class='bx bxs-home'></i>
                        <span class="links_name">Home</span>
                    </a>
                    <span class="tooltip">Home</span>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Resennia")">
                        <i class='bx bx-comment-dots'></i>
                        <span class="links_name">Reseñas</span>
                    </a>
                    <span class="tooltip">Reseñas</span>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Reserva")">
                        <i class='bx bx-book-content'></i>
                        <span class="links_name">Reservas</span>
                    </a>
                    <span class="tooltip">Reservas</span>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Servicio")">
                        <i class='bx bx-briefcase-alt-2'></i>
                        <span class="links_name">Servicios</span>
                    </a>
                    <span class="tooltip">Servicios</span>
                </li>
                <li>
                    <a href="@Url.Action("About", "Home")">
                        <i class='bx bx-detail'></i>
                        <span class="links_name">Accerca</span>
                    </a>
                    <span class="tooltip">Accerca</span>
                </li>
            }
        </ul>
        @*User part*@
        @if (User.IsInRole("Cliente") || User.IsInRole("Admin"))
        {
            <div class="profile_content">
                <div class="profile">
                    <div class="profile_details">
                        <div class="name_job">
                            <div class="name">@Html.Partial("_LoginPartial")</div>
                        </div>
                    </div>
                    <div class="job"><a href="javascript:document.getElementById('logoutForm').submit()"><i class="bx bx-log-out" id="log_out"></i></a></div>
                </div>
            </div>
        }
        else
        {
            <div class="profile_content">
                <div class="profile">
                    <div class="profile_details">
                        <div class="name_job">
                            <div class="name">@Html.Partial("_LoginPartial")</div>
                        </div>
                    </div>
                    <i class='bx bx-log-in' id="log_out"></i>
                </div>
            </div>
        }
    </div>

    <div class="container body-content">
        @RenderBody()

    </div>

    <script>
        let btn = document.querySelector("#btn");
        let log = document.querySelector("#log_out");

        let sidebar = document.querySelector(".sidebar");

        btn.onclick = function () {
            sidebar.classList.toggle("active");
        };

        log_out.onclick = function () {
            sidebar.classList.toggle("active");
        };
    </script>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>