webHibiscus/Controllers/AspNetUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webHibiscus;

namespace webHibiscus.Controllers
{
    public class AspNetUsersController : Controller
    {
        private webHibiscuEntities db = new webHibiscuEntities();

        // GET: AspNetUsers
        public ActionResult Index()
        {
            var aspNetUsers = db.AspNetUsers.Include(a => a.Genero);
            return View(aspNetUsers.ToList());
        }

        // GET: AspNetUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Create
        public ActionResult Create()
        {
            ViewBag.idGenero = new SelectList(db.Generoes, "id_Genero", "Genero1");
            return View();
        }

        // POST: AspNetUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,nombre,apellido1,apellido2,cedula_Usuario,telefono,idGenero")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idGenero = new SelectList(db.Generoes, "id_Genero", "Genero1", aspNetUser.idGenero);
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.idGenero = new SelectList(db.Generoes, "id_Genero", "Genero1", aspNetUser.idGenero);
            return View(aspNetUser);
        }

        // POST: AspNetUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,nombre,apellido1,apellido2,cedula_Usuario,telefono,idGenero")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idGenero = new SelectList(db.Generoes, "id_Genero", "Genero1", aspNetUser.idGenero);
            return View(aspNetUser);
        }

        // GET: AspNetUsers/LoginEdit/5
        public ActionResult LoginEdit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.idGenero = new SelectList(db.Generoes, "id_Genero", "Genero1", aspNetUser.idGenero);
            return View(aspNetUser);
        }

        // POST: AspNetUsers/LoginEdit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoginEdit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,nombre,apellido1,apellido2,cedula_Usuario,telefono,idGenero")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            ViewBag.idGenero = new SelectList(db.Generoes, "id_Genero", "Genero1", aspNetUser.idGenero);
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webHibiscus/Views/AspNetUsers/Delete.cshtml
@model webHibiscus.AspNetUser

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Esta seguro que desea eliminar el usuario: @Html.DisplayFor(model => model.UserName) ?</h2>


<div>
     <div class="row">

<div class="card table-responsive" style="border-radius: 8px;">
         <table class="table table-striped">
            <tr>
                <td>
                    <b>
                        <h4> Usuario </h4>
                    </b>
                </td>
                <td>
                    <h4>
                        @Html.DisplayFor(model => model.UserName)
                    </h4>
            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Nombre</h4>
                    </b>
                </td>
                <td>
                    <h4>
                        @Html.DisplayFor(model => model.nombre)
                    </h4>
            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Primer apellido</h4>
                    </b>
                </td>
                <td>
                    <h4>
                        @Html.DisplayFor(model => model.apellido1)
                    </h4>
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Segundo apellido</h4>
                    </b>
                </td>
                <td>
                    <h4>
                        @Html.DisplayFor(model => model.apellido2)
                    </h4>
                </td>
            </tr>

            <tr>
                <td>
                    <b>
                        <h4>Cedula</h4>
                    </b>
                </td>
                <td>
                    <h4>
                        @Html.DisplayFor(model => model.cedula_Usuario)
                    </h4>
            <tr>
                <td>
                    <b>
                        <h4>Email</h4>
                    </b>
                </td>
                <td>
                    <h4>
                                @Html.DisplayFor(model => model.Email)
                    </h4>
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Telefono</h4>
                    </b>
                </td>
                <td>
                    <h4>
                                @Html.DisplayFor(model => model.telefono)
                    </h4>
                </td>

            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Genero</h4>
                    </b>
                </td>
                <td>
                    <h4>
                                @Html.DisplayFor(model => model.Genero.Genero1)
                    </h4>
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Accesos erroneos</h4>
                    </b>
                </td>
                <td>
                    <h4>
                                @Html.DisplayFor(model => model.AccessFailedCount)
                    </h4>
                </td>
            </tr>
        </table>
    </div>
</div>
</div>

    @* <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellido1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellido1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellido2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellido2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cedula_Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cedula_Usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genero.Genero1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero.Genero1)
        </dd>

    </dl> *@

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
              <a href="@Url.Action("Index", "AspNetUsers")" class="btn btn-info">Volver atras</a>
            <input type="submit" value="Borrar" class="btn btn-danger" /> 
           
        </div>
    }
</div>

webHibiscus/Views/AspNetUsers/Details.cshtml
@model webHibiscus.AspNetUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles de Usuario</h2>

<div>


    <div class="row">

<div class="card table-responsive" style="border-radius: 8px;">
         <table class="table table-striped">
            <tr>
                <td>
                    <b>
                        <h4> Usuario </h4>
                    </b>
                </td>
                <td>
                    <h4>
                        @Html.DisplayFor(model => model.UserName)
                    </h4>
            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Nombre</h4>
                    </b>
                </td>
                <td>
                    <h4>
                        @Html.DisplayFor(model => model.nombre)
                    </h4>
            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Primer apellido</h4>
                    </b>
                </td>
                <td>
                    <h4>
                        @Html.DisplayFor(model => model.apellido1)
                    </h4>
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Segundo apellido</h4>
                    </b>
                </td>
                <td>
                    <h4>
                        @Html.DisplayFor(model => model.apellido2)
                    </h4>
                </td>
            </tr>

            <tr>
                <td>
                    <b>
                        <h4>Cedula</h4>
                    </b>
                </td>
                <td>
                    <h4>
                        @Html.DisplayFor(model => model.cedula_Usuario)
                    </h4>
            <tr>
                <td>
                    <b>
                        <h4>Email</h4>
                    </b>
                </td>
                <td>
                    <h4>
                                @Html.DisplayFor(model => model.Email)
                    </h4>
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Telefono</h4>
                    </b>
                </td>
                <td>
                    <h4>
                                @Html.DisplayFor(model => model.telefono)
                    </h4>
                </td>

            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Genero</h4>
                    </b>
                </td>
                <td>
                    <h4>
                                @Html.DisplayFor(model => model.Genero.Genero1)
                    </h4>
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                        <h4>Accesos erroneos</h4>
                    </b>
                </td>
                <td>
                    <h4>
                                @Html.DisplayFor(model => model.AccessFailedCount)
                    </h4>
                </td>
        </table>
    </div>
    @* <dt>
        @Html.DisplayNameFor(model => model.Email)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Email)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.EmailConfirmed)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.EmailConfirmed)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.PasswordHash)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.PasswordHash)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.SecurityStamp)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SecurityStamp)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.PhoneNumber)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.PhoneNumber)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.PhoneNumberConfirmed)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.TwoFactorEnabled)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.TwoFactorEnabled)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.LockoutEndDateUtc)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.LockoutEnabled)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.LockoutEnabled)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.AccessFailedCount)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.AccessFailedCount)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.UserName)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.UserName)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.nombre)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.nombre)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.apellido1)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.apellido1)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.apellido2)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.apellido2)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.cedula_Usuario)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.cedula_Usuario)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.telefono)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.telefono)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Genero.Genero1)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Genero.Genero1)
    </dd>

    </dl> *@
</div>
</div>
<p>
       <a href="@Url.Action("Index", "AspNetUsers")" class="btn btn-info">Volver</a>
     <a class="btn btn-warning"
           href="@Url.Action("Edit", "AspNetUsers", new { id = Model.Id }) ">Editar</a>
   
   
</p>

webHibiscus/Views/AspNetUsers/Edit.cshtml
@model webHibiscus.AspNetUser

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Editando a @Model.nombre @Model.apellido1 @Model.apellido2</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    @Html.HiddenFor(model => model.EmailConfirmed)
    @Html.ValidationMessageFor(model => model.EmailConfirmed, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.SecurityStamp, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.SecurityStamp, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.PhoneNumberConfirmed)
    @Html.ValidationMessageFor(model => model.PhoneNumberConfirmed, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.TwoFactorEnabled)
    @Html.ValidationMessageFor(model => model.TwoFactorEnabled, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.LockoutEndDateUtc, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.LockoutEndDateUtc, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.LockoutEnabled)
    @Html.ValidationMessageFor(model => model.LockoutEnabled, "", new { @class = "text-danger" })









<div class="form-group">














    <div class="form-group">
       <h4> @Html.LabelFor(model => model.Email,"Correo Electronico", htmlAttributes: new { @class = "control-label col-md-2" })</h4>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
    <h4>    @Html.LabelFor(model => model.AccessFailedCount,"Accesos Erroneos", htmlAttributes: new { @class = "control-label col-md-2" })</h4>
        <div class="col-md-10">
            @Html.EditorFor(model => model.AccessFailedCount, new { htmlAttributes = new { @class = "form-control", ReadOnly="true"  } })
            @Html.ValidationMessageFor(model => model.AccessFailedCount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
      <h4>  @Html.LabelFor(model => model.UserName, "Nombre Usuario",htmlAttributes: new { @class = "control-label col-md-2" })</h4>
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
      <h4>  @Html.LabelFor(model => model.nombre,"Nombre", htmlAttributes: new { @class = "control-label col-md-2" })</h4>    
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
     <h4>   @Html.LabelFor(model => model.apellido1, "Primer Apellido",htmlAttributes: new { @class = "control-label col-md-2" })</h4>
        <div class="col-md-10">
            @Html.EditorFor(model => model.apellido1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.apellido1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
       <h4> @Html.LabelFor(model => model.apellido2,"Segundo Apellido" ,htmlAttributes: new { @class = "control-label col-md-2" })</h4>
        <div class="col-md-10">
            @Html.EditorFor(model => model.apellido2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.apellido2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
    <h4>    @Html.LabelFor(model => model.cedula_Usuario,"Cedula" ,htmlAttributes: new { @class = "control-label col-md-2" })</h4>
        <div class="col-md-10">
            @Html.EditorFor(model => model.cedula_Usuario, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cedula_Usuario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
       <h4> @Html.LabelFor(model => model.telefono,"Telefono" ,htmlAttributes: new { @class = "control-label col-md-2" })</h4>
        <div class="col-md-10">
            @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
      <h4>  @Html.LabelFor(model => model.idGenero, "Genero", htmlAttributes: new { @class = "control-label col-md-2" })</h4>

        <div class="col-md-10">
            @Html.DropDownList("idGenero", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idGenero, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-success" />
        </div>
    </div>
</div>
</div>
}

<div>
    <a class="btn btn-info" href="@Url.Action("Index", "AspNetUsers")" class="btn btn-default">Volver atras</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

webHibiscus/Views/AspNetUsers/Index.cshtml
@model IEnumerable<webHibiscus.AspNetUser>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>
    <div class="row">
        <h2>Usuarios</h2>
        
    </div>


    <div class="card table-responsive" style="border-radius: 8px;">

        <div style="margin-left:2%">

            <br>
            <input type="text" id="busquedaNombre" onkeyup="myFunction()" placeholder="Buscar usuario...">
            <br>
            <br>

        </div>

        <table class="table table-striped" id="tablaUsuarios" onclick="pulguis()">

            <tr>
                <th colspan="3" style="text-align: center;">
                    <p>Nombre Completo</p>
                </th>


                <th>
                    <p>Nombre Usuario</p>
                </th>

                <th>
                    <p> Correo Electronico</p>
                </th>
                <th>
                    <p>Cedula</p>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.telefono)
                </th>
                <th>
                    <p>Genero</p>
                </th>
                <th colspan="3" style="text-align: center;">
                    <p>Acciones</p>
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.apellido1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.apellido2)
                    </td>


                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cedula_Usuario)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.telefono)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Genero.Genero1)
                    </td>
                    <td>

                        <a class="btn btn-info btn-small" href="@Url.Action("Details", new { id = item.Id })">Detalles</a>

                    </td>
                    <td>
                        <a class="btn btn-warning btn-small" href="@Url.Action("Edit", new { id = item.Id })">Editar</a>
                    </td>
                    <td>
                        <a class="btn btn-danger btn-small" href="@Url.Action("Delete", new{ id = item.Id})">Eliminar</a>
                    </td>
                </tr>
            }

        </table>

        <script src="~/Scripts/javaScriptIndexUsuarios.js"></script>

    </div>

</div>