webHibiscus/Controllers/AspNetRoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webHibiscus;

namespace webHibiscus.Controllers
{
    public class AspNetRoleController : Controller
    {
        private webHibiscuEntities db = new webHibiscuEntities();

        // GET: AspNetRole
        public ActionResult Index()
        {
            return View(db.AspNetRoles.ToList());
        }

        // GET: AspNetRole/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }

        // GET: AspNetRole/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetRole/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] AspNetRole aspNetRole)
        {
            if (ModelState.IsValid)
            {
                db.AspNetRoles.Add(aspNetRole);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetRole);
        }

        // GET: AspNetRole/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }

        // POST: AspNetRole/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] AspNetRole aspNetRole)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetRole).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetRole);
        }

        // GET: AspNetRole/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }

        // POST: AspNetRole/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            db.AspNetRoles.Remove(aspNetRole);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webHibiscus/Views/AspNetRole/Create.cshtml
@model webHibiscus.AspNetRole

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Creando Rol</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
           <h4> @Html.LabelFor(model => model.Id,htmlAttributes: new { @class = "control-label col-md-2" })</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
          <h4>  @Html.LabelFor(model => model.Name,"Nombre", htmlAttributes: new { @class = "control-label col-md-2" })</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-info" href="@Url.Action("Index", "AspNetRole")">Volver</a>
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

webHibiscus/Views/AspNetRole/Delete.cshtml
@model webHibiscus.AspNetRole

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>¿Seguro que quieres eliminar esté rol?</h2>

<div>
 <div>
    <div class="card table-responsive" style="border-radius: 8px;">
        <table class="table table-striped">
            <tr>
                <th>
                    <h4>
                        <b>
                             @Html.DisplayNameFor(model => model.Name)
                        </b>
                    </h4>
                </th>
                <th>
                    <h4>
                        <b>
                            @Html.DisplayFor(model => model.Name)
                        </b>
                    </h4>
                </th>
          
            </tr>           
        </table>
    </div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <a href="@Url.Action("Index", "AspNetRole")" class="btn btn-success">Volver atrás</a>
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            
        </div>
    }
</div>

webHibiscus/Views/AspNetRole/Details.cshtml
@model webHibiscus.AspNetRole

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles</h2>

<div>
    <div class="card table-responsive" style="border-radius: 8px;">
        <table class="table table-striped">
            <tr>
                <th>
                    <h4>
                        <b>
                             @Html.DisplayNameFor(model => model.Name)
                        </b>
                    </h4>
                </th>
                <th>
                    <h4>
                        <b>
                            @Html.DisplayFor(model => model.Name)
                        </b>
                    </h4>
                </th>
          
            </tr>           
        </table>
    </div>
</div>

<p>

    
    <a class="btn btn-info" href="@Url.Action("Index", "AspNetRole")">
      Volver atras
    </a>
    <a class="btn btn-warning" href="@Url.Action("Edit", "AspNetRole", new { id = Model.Id })">
      Editar
    </a>
</p>

webHibiscus/Views/AspNetRole/Edit.cshtml
@model webHibiscus.AspNetRole

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editando el rol de: @Model.Name</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
          <h4>  @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-info" href="@Url.Action("Index", "AspNetRole")">Volver atras</a> 
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

webHibiscus/Views/AspNetRole/Index.cshtml
@model IEnumerable<webHibiscus.AspNetRole>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Roles</h2>

<p>
    <a class="btn btn-info" href="@Url.Action("Create")">Crear nuevo rol</a>

</p>
<div class="card table-responsive" style="border-radius: 8px;">
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th colspan=""></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a class="btn btn-info" href="@Url.Action("Details", new { id = item.Id })">Detalles</a>
          
                <a class="btn btn-warning" href="@Url.Action("Edit", new { id = item.Id })">Editar</a>
                
           
                <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.Id })">Eliminar</a>
                
            </td>
        </tr>
    }

</table>